services:
  db:
    image: postgres:16
    container_name: fastapi_example_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=oli98
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - fastapi_example_network
  fastapi_example_backend:
    build: .
    container_name: fastapi_example_backend
    restart: always
    stdin_open: true
    tty: true
    ports: 
      - "8000:8000"  # Remove external port exposure
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=oli98
      - DB_PASSWORD=password
      - DB_NAME=postgres
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - fastapi_example_network
volumes:
  postgres_data:
networks:
  fastapi_example_network:
    driver: bridge